import { invoke, convertFileSrc, isTauri } from "@tauri-apps/api/core";
import type { Command } from "../bindings/Command";
import type { Bootstrap } from "../bindings/Bootstrap";
import type { CardView } from "../bindings/CardView";
import type { CardPage } from "../bindings/CardPage";
import type { StudyView } from "../bindings/StudyView";
import type { ReviewEvent } from "../bindings/ReviewEvent";
import type { Statistics } from "../bindings/Statistics";
import type { ImportPreview } from "../bindings/ImportPreview";
import type { ImportResult } from "../bindings/ImportResult";
import type { BackupInfo } from "../bindings/BackupInfo";
import type { IntegrityReport } from "../bindings/IntegrityReport";
import type { FileSelection } from "../bindings/FileSelection";

// Keep result types aligned with api::execute; request/payload types are generated by ts-rs.
type Responses = {
  bootstrap: Bootstrap;
  editor_dirty: null;
  quit_app: null;
  save_deck: string;
  delete_deck: null;
  save_note: CardView;
  get_card: CardView;
  browse: CardPage;
  bulk: number;
  edit_tag: null;
  start_study: StudyView;
  study: StudyView | null;
  review: StudyView;
  undo: string;
  history: ReviewEvent[];
  statistics: Statistics;
  save_preferences: null;
  attach_file: string;
  attach_bytes: string;
  preview_import: ImportPreview;
  commit_import: ImportResult;
  export_delimited: number;
  export_native: null;
  backups: BackupInfo[];
  create_backup: BackupInfo;
  restore_backup: null;
  restore_file: null;
  integrity: IntegrityReport;
  repair_indexes: IntegrityReport;
  recover_collection: boolean;
  cleanup_media: number;
  export_diagnostics: null;
  open_data_directory: null;
};
/** The only collection RPC surface; Rust validates content and owns persistence. */
export function rpc<C extends Command & { action: keyof Responses }>(
  request: C,
): Promise<Responses[C["action"]]> {
  return invoke("dispatch", { request });
}
export const pickFile = (purpose: "image" | "import" | "restore") =>
  invoke<FileSelection | null>("pick_file", { purpose });
export const saveFile = (
  purpose: "delimited" | "native" | "diagnostics",
  name: string,
) => invoke<FileSelection | null>("save_file", { purpose, name });
export const openExternal = (url: string) =>
  invoke<void>("open_external", { url });
export const native = isTauri;
// Resolve asset URLs at display time; saved documents contain only media IDs.
export const mediaUrl = (directory: string, id: string | null | undefined) =>
  id ? convertFileSrc(`${directory}/${id}`) : undefined;
export function errorMessage(error: unknown): string {
  if (typeof error === "object" && error && "message" in error)
    return String(error.message);
  return typeof error === "string"
    ? error
    : "Something went wrong. Please try again.";
}
