// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../src-tauri/bindings/serde_json/JsonValue";
import type { Behavior } from "./Behavior";

export type AnkiPreviewCard = { number: number, deckPath: string, front: JsonValue, back: JsonValue, behavior: Behavior, tags: Array<string>, duplicate: boolean, error: string | null, };
