// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnkiDestination } from "./AnkiDestination";
import type { AnkiPreviewCard } from "./AnkiPreviewCard";

export type AnkiImportPreview = { digest: string, total: number, duplicates: number, affected: number, audioFiles: number, audioAssets: number, imageFiles: number, decks: Array<AnkiDestination>, cards: Array<AnkiPreviewCard>, warnings: Array<string>, issues: Array<string>, blockingErrors: Array<string>, };
