// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnkiImportConfig = { pathToken: string, parentId: string | null, duplicates: string, skipAffected: boolean, destinations: { [key in string]?: string }, previewDigest: string | null, };
