// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deck } from "./Deck";
import type { Preferences } from "./Preferences";
import type { SessionRecord } from "./SessionRecord";
import type { Today } from "./Today";

export type Bootstrap = { decks: Array<Deck>, tags: Array<string>, preferences: Preferences, today: Today, mediaDir: string, dataDir: string, backupWarning: string | null, undoLabel: string | null, session: SessionRecord | null, };
