// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowseQuery = { search: string, deck: string | null, tag: string | null, state: string | null, leech: boolean, trash: boolean, sort: string, descending: boolean, offset: number, limit: number, };
