// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardView } from "./CardView";

export type CardPage = { cards: Array<CardView>, total: number, };
