// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../src-tauri/bindings/serde_json/JsonValue";
import type { Behavior } from "./Behavior";
import type { Schedule } from "./Schedule";

export type CardView = { id: string, noteId: string, deckId: string, deckName: string, front: JsonValue, back: JsonValue, frontText: string, backText: string, behavior: Behavior, tags: Array<string>, schedule: Schedule, suspended: boolean, buriedUntil: number | null, leech: boolean, createdAt: number, modifiedAt: number, revision: number, deletedAt: number | null, };
