// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeckSettings } from "./DeckSettings";

export type Deck = { id: string, name: string, cover: string | null, color: string, settings: DeckSettings, createdAt: number, updatedAt: number, total: number, newCount: number, learning: number, review: number, due: number, inReview: number, limitedNew: number, limitedReview: number, };
