// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeckSettings } from "./DeckSettings";

export type DeckInput = { id: string | null, name: string, parentId: string | null, cover: string | null, color: string, settings: DeckSettings, };
