// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeckSettings = { newLimit: number, reviewLimit: number, retention: number, learningSteps: Array<number>, relearningSteps: Array<number>, maximumInterval: number, newOrder: string, reviewOrder: string, newPlacement: string, leechThreshold: number, suspendLeeches: boolean, };
