// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeckCounts = { total: number, newCount: number, learning: number, review: number, due: number, inReview: number, limitedNew: number, limitedReview: number, };
