// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schedule } from "./Schedule";

export type GradeOption = { grade: number, label: string, interval: string, schedule: Schedule, };
