// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Behavior } from "./Behavior";

export type ImportConfig = { pathToken: string, delimiter: string, hasHeader: boolean, frontColumn: number, backColumn: number, tagsColumn: number | null, deckId: string, behavior: Behavior, duplicates: string, previewDigest: string | null, };
