// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportRow } from "./ImportRow";

export type ImportPreview = { rows: Array<ImportRow>, total: number, duplicates: number, errors: Array<string>, headers: Array<string>, digest: string, };
