// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntegrityReport = { healthy: boolean, issues: Array<string>, missingMedia: Array<string>, unusedMedia: Array<string>, };
