// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../src-tauri/bindings/serde_json/JsonValue";
import type { Behavior } from "./Behavior";

export type NoteInput = { id: string | null, deckId: string, front: JsonValue, back: JsonValue, behavior: Behavior, tags: Array<string>, };
