// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schedule } from "./Schedule";

export type ReviewEvent = { id: string, cardId: string, deckName: string, timestamp: number, day: string, grade: number, before: Schedule, after: Schedule, durationMs: number, undoneAt: number | null, scheduler: string, };
