// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewInput = { sessionId: string, cardId: string, revision: number, operationId: string, grade: number, durationMs: number, };
