// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";

export type Schedule = { phase: Phase, due: number, stability: number | null, difficulty: number | null, scheduledDays: number, reviewCount: number, lapses: number, lastReview: number | null, step: number, };
