// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable membership makes progress meaningful even when cards repeat or become ineligible.
 */
export type SessionRecord = { id: string, day: string, deckId: string | null, cardIds: Array<string>, completed: Array<string>, skipped: Array<string>, };
