// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayStat } from "./DayStat";
import type { Deck } from "./Deck";
import type { PeriodSummary } from "./PeriodSummary";
import type { StateStat } from "./StateStat";

export type Statistics = { summary: PeriodSummary, previous: PeriodSummary, currentStreak: number, longestStreak: number, days: Array<DayStat>, grades: Array<StateStat>, states: Array<StateStat>, decks: Array<Deck>, forecast: Array<DayStat>, estimatedRetention: number | null, averageStability: number | null, averageDifficulty: number | null, };
