// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardView } from "./CardView";
import type { GradeOption } from "./GradeOption";
import type { SessionRecord } from "./SessionRecord";

export type StudyView = { session: SessionRecord, card: CardView | null, options: Array<GradeOption>, nextDue: number | null, finished: boolean, };
