// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Today = { newCount: number, learning: number, review: number, studied: number, streak: number, nextDue: number | null, };
